/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Aryaa
 */
public class PAJAK extends javax.swing.JFrame {

    /**
     * Creates new form PAJAK
     */
    public PAJAK() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        fgaji = new javax.swing.JTextField();
        fhitungpajak = new javax.swing.JTextField();
        fkendaraan = new javax.swing.JTextField();
        btnhitung = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(48, 133, 195));
        jPanel1.setLayout(new java.awt.BorderLayout());

        jLabel1.setBackground(new java.awt.Color(48, 133, 195));
        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("PAJAK");
        jPanel1.add(jLabel1, java.awt.BorderLayout.PAGE_START);

        jPanel2.setLayout(new java.awt.GridLayout());

        jPanel3.setBackground(new java.awt.Color(244, 232, 105));
        jPanel3.setLayout(new java.awt.GridLayout(4, 0));

        jLabel2.setBackground(new java.awt.Color(158, 221, 255));
        jLabel2.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("GAJI");
        jPanel3.add(jLabel2);

        jLabel3.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("HITUNG PAJAK");
        jPanel3.add(jLabel3);

        jLabel4.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("KENDARAAN");
        jPanel3.add(jLabel4);

        jPanel2.add(jPanel3);

        jPanel4.setLayout(new java.awt.GridLayout(4, 0));

        fgaji.setBackground(new java.awt.Color(250, 242, 211));
        jPanel4.add(fgaji);

        fhitungpajak.setEditable(false);
        fhitungpajak.setBackground(new java.awt.Color(250, 242, 211));
        jPanel4.add(fhitungpajak);

        fkendaraan.setBackground(new java.awt.Color(250, 242, 211));
        jPanel4.add(fkendaraan);

        btnhitung.setBackground(new java.awt.Color(250, 242, 211));
        btnhitung.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        btnhitung.setText("HITUNG");
        btnhitung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnhitungActionPerformed(evt);
            }
        });
        jPanel4.add(btnhitung);

        jPanel2.add(jPanel4);

        jPanel1.add(jPanel2, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 516, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 381, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnhitungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnhitungActionPerformed
        // TODO add your handling code here:
        Integer gaji = Integer.parseInt(fgaji.getText());
        Integer kendaraan = Integer.parseInt(fkendaraan.getText());
        
        if(gaji >= 10000000 && kendaraan >= 3){
            Double pajak = (double) gaji * 0.15;
            int pjk = (int) Math.floor(pajak);
            fhitungpajak.setText(Integer.toString(pjk));
        }else if (gaji >= 5000000){
            if(kendaraan == 2){
                Double pajak = (double) gaji * 0.1;
                int pjk = (int) Math.floor(pajak);
            fhitungpajak.setText(Integer.toString(pjk));
            }else if (kendaraan == 1){
                Double pajak = (double) gaji * 0.07;
                int pjk = (int) Math.floor(pajak);
                fhitungpajak.setText(Integer.toString(pjk));
            }else{
                fhitungpajak.setText("Gaji Anda " + Integer.toString(gaji) + " Maka Masukkan Jumlah Kendaraan");
            }
        }else if (gaji < 5000000){
            if(kendaraan == 1){
                Double pajak = (double) gaji * 0.05;
                int pjk = (int) Math.floor(pajak);
                fhitungpajak.setText(Integer.toString(pjk));
            }else {
                Double pajak = (double) gaji * 0.025;
                int pjk = (int) Math.floor(pajak);
                fhitungpajak.setText(Integer.toString(pjk));
            }
        }
    }//GEN-LAST:event_btnhitungActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PAJAK.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PAJAK.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PAJAK.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PAJAK.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PAJAK().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnhitung;
    private javax.swing.JTextField fgaji;
    private javax.swing.JTextField fhitungpajak;
    private javax.swing.JTextField fkendaraan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    // End of variables declaration//GEN-END:variables
}
