/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Aryaa
 */
public class PERPUSTAKAAN extends javax.swing.JFrame {

    /**
     * Creates new form PERPUSTAKAAN
     */
    public PERPUSTAKAAN() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        judul = new javax.swing.JLabel();
        penerbit = new javax.swing.JLabel();
        penulis = new javax.swing.JLabel();
        tahunterbit = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        btndaftar = new javax.swing.JComboBox<>();
        fperpus = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        fjudul = new javax.swing.JTextField();
        fpenerbit = new javax.swing.JTextField();
        fpenulis = new javax.swing.JTextField();
        ftahun = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 128, 128));
        jPanel1.setLayout(new java.awt.BorderLayout());

        jPanel3.setBackground(new java.awt.Color(246, 253, 195));

        judul.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        judul.setText("JUDUL");

        penerbit.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        penerbit.setText("PENERBIT");

        penulis.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        penulis.setText("PENULIS");

        tahunterbit.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        tahunterbit.setText("TAHUN TERBIT");

        jPanel5.setBackground(new java.awt.Color(255, 207, 150));

        btndaftar.setBackground(new java.awt.Color(205, 250, 213));
        btndaftar.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        btndaftar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "DAFTAR BUKU", "THE ALCHEMIST", "THE HOBBIT", "HARRY POTTER ", "THE GREAT GATSBY", " " }));
        btndaftar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndaftarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btndaftar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(116, 116, 116)
                .addComponent(btndaftar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(judul)
                            .addComponent(penulis)
                            .addComponent(penerbit))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(tahunterbit)
                        .addContainerGap())))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(judul)
                .addGap(61, 61, 61)
                .addComponent(penerbit)
                .addGap(57, 57, 57)
                .addComponent(penulis)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addComponent(tahunterbit)
                .addGap(20, 20, 20))
            .addComponent(jPanel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel3, java.awt.BorderLayout.LINE_START);

        fperpus.setBackground(new java.awt.Color(0, 102, 102));
        fperpus.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        fperpus.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        fperpus.setText("PERPUSTAKAAN MERDEKA");
        jPanel1.add(fperpus, java.awt.BorderLayout.PAGE_START);

        jPanel2.setLayout(new java.awt.BorderLayout());

        jPanel4.setLayout(new java.awt.GridLayout(4, 0));

        fjudul.setBackground(new java.awt.Color(205, 250, 213));
        jPanel4.add(fjudul);

        fpenerbit.setBackground(new java.awt.Color(205, 250, 213));
        jPanel4.add(fpenerbit);

        fpenulis.setBackground(new java.awt.Color(205, 250, 213));
        jPanel4.add(fpenulis);

        ftahun.setBackground(new java.awt.Color(205, 250, 213));
        jPanel4.add(ftahun);

        jPanel2.add(jPanel4, java.awt.BorderLayout.CENTER);

        jPanel1.add(jPanel2, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 472, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void cetak(String judul,String penerbit,String penulis,String tahun){
        fjudul.setText(judul);
        fpenerbit.setText(penerbit);
        fpenulis.setText(penulis);
        ftahun.setText(tahun);
    }
    private void btndaftarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndaftarActionPerformed
        // TODO add your handling code here:
        String tipe = btndaftar.getSelectedItem().toString();
        
        switch(tipe){
            case"THE ALCHEMIST"->{
                cetak("The alchemist", "HarperOne", "Paulo Coelho", "1988");
            }    
            case"THE HOBBIT"->{
                cetak("The hobbit", "George allen&unwin", "J.RR.tOlkien", "1937");
            } 
            case"HARRY POTTER "->{
                cetak("harry potter", "bloomsbury", "J.K.Rowling", "1997");  
            }
            case"THE GREAT GATSBY"->{
                cetak("THE GREAT GATSBY", "charles scribners sons", "F.scoot fitzgerald", "1925");
            }
            default->{
            }
        }
    }//GEN-LAST:event_btndaftarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PERPUSTAKAAN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PERPUSTAKAAN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PERPUSTAKAAN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PERPUSTAKAAN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PERPUSTAKAAN().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> btndaftar;
    private javax.swing.JTextField fjudul;
    private javax.swing.JTextField fpenerbit;
    private javax.swing.JTextField fpenulis;
    private javax.swing.JLabel fperpus;
    private javax.swing.JTextField ftahun;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JLabel judul;
    private javax.swing.JLabel penerbit;
    private javax.swing.JLabel penulis;
    private javax.swing.JLabel tahunterbit;
    // End of variables declaration//GEN-END:variables
}
